SELECT 
SUM(TOTAL_FEES) AS TOTAL_EXPECTED,
SUM(AMOUNT_PAID) AS TOTAL_COLLECTED,
SUM(BALANCE_OUTSTANDING) AS TOTAL_OUTSTANDNG
FROM FEES;
--TOTAL REVENUE VS COLLECTED REVENUE



SELECT GRADE, SUM(AMOUNT_PAID) AS REVENUE
FROM FEES
GROUP BY GRADE 
ORDER BY REVENUE DESC;
-- REVENUE BY GRADE



SELECT GRADE, SUM(BALANCE_OUTSTANDING) AS OUTSTANDING
FROM FEES
GROUP BY GRADE ORDER BY OUTSTANDING DESC;
--OUTSTANDING FEES BY GRADE


SELECT TOP 10 STUDENT_NAME, BALANCE_OUTSTANDING FROM FEES
ORDER BY BALANCE_OUTSTANDING DESC;
-- TOP DEFAULTERS


SELECT SUM(BALANCE_OUTSTANDING) AS TOTAL_TOP10_BALANCE
FROM(
	SELECT TOP 10 STUDENT_NAME, BALANCE_OUTSTANDING FROM FEES
	ORDER BY BALANCE_OUTSTANDING DESC
) AS TOP10;
--TOP DEFAULTERS SUM



SELECT SUM(AMOUNT) AS TOTAL_EXPENDITURE
FROM EXPENSES
--TOTAL EXPENDITURE


SELECT CATEGORY, SUM(AMOUNT) AS TOTAL_SPENT
FROM EXPENSES
GROUP BY CATEGORY
ORDER BY TOTAL_SPENT DESC
-- EXPENDITURE BY CATEGORY


SELECT DATENAME(MONTH,[DATE]) AS MONTH_NAME, SUM(AMOUNT) AS TOTAL
FROM EXPENSES
GROUP BY DATENAME(MONTH,[DATE]), MONTH([DATE])
ORDER BY MONTH([DATE])
---TOTAL EXPENDITURE BY MONTH


SELECT 
	(SELECT SUM(AMOUNT_PAID) FROM FEES) AS TOTAL_COLLECTED,
	(SELECT SUM(AMOUNT) FROM EXPENSES) AS TOTAL_EXPENSES,
	(SELECT SUM(AMOUNT_PAID) FROM FEES) - (SELECT SUM(AMOUNT) FROM EXPENSES) AS PROFIT
--PROFIT

SELECT 
	TOTAL_COLLECTED,
	TOTAL_EXPENSES,
	PROFIT,
	(PROFIT * 1.0/TOTAL_COLLECTED)* 100 AS PROFIT_MARGIN_PERCENT
FROM (
	SELECT
		(SELECT SUM(AMOUNT_PAID) FROM FEES) AS TOTAL_COLLECTED,
		(SELECT SUM(AMOUNT) FROM EXPENSES) AS TOTAL_EXPENSES,
		(SELECT SUM(AMOUNT_PAID) FROM FEES) - (SELECT SUM(AMOUNT) FROM EXPENSES) AS PROFIT
	) T;
-- PROFIT MARGIN


WITH MONTHLYEXPENSES AS (
    SELECT 
        MONTH([DATE]) AS Month,
        SUM(AMOUNT) AS TOTAL_EXPENSES
    FROM EXPENSES
    GROUP BY MONTH([DATE])
)

SELECT * 
FROM MONTHLYEXPENSES
ORDER BY MONTH;
--MONTHLY EXPENSES



WITH MONTHLYEXPENSES AS (
    SELECT 
        MONTH([DATE]) AS MONTH,
        SUM(AMOUNT) AS TOTAL_EXPENSES
    FROM EXPENSES
    GROUP BY MONTH([DATE])
)

SELECT *
FROM MONTHLYEXPENSES
WHERE TOTAL_EXPENSES > 250000
ORDER BY TOTAL_EXPENSES DESC;
-- HIGH SPENDING MONTHS



WITH DAILYEXPENSES AS (
    SELECT 
        [DATE],
        SUM(AMOUNT) AS DAILY_TOTAL
    FROM EXPENSES
    GROUP BY [DATE]
)

SELECT 
    [DATE],
    DAILY_TOTAL,
    SUM(DAILY_TOTAL) OVER (ORDER BY [DATE]) AS RUNNING_TOTAL
FROM DAILYEXPENSES;
--ACCUMULATION OVER TIME



-- BREAK-EVEN ANALYSIS

WITH FIXEDCOSTS AS (
    SELECT SUM(AMOUNT) AS TOTAL_FIXED
    FROM EXPENSES
    WHERE DESCRIPTION IN ('Building & Construction', 'Salaries & Wages', 'Rent Expenses', 'Loans', 'Utilities', 'Miscallenous')
)
SELECT * FROM FIXEDCOSTS;
--FIXED COSTS CALCULATION



WITH VARIABLECOSTS AS (
    SELECT SUM(AMOUNT) AS TOTAL_VARIABLE
    FROM EXPENSES
    WHERE DESCRIPTION IN ('Kitchen Expenses', 'Transport Expenses', 'Learning Materials', 'Maintenance Supplies')
)
SELECT * FROM VariableCosts;
-- VARIABLE COST CALCULATION



SELECT 
    SUM(AMOUNT) / 220 AS VARIABLE_COST_PER_STUDENT
FROM EXPENSES
WHERE DESCRIPTION IN ('Kitchen Expenses', 'Transport Expenses', 'Learning Materials', 'Maintenance Supplies');
-- COST PER STUDENT



SELECT 
    AVG(TOTAL_FEES) AS FEE_PER_STUDENT
FROM FEES;
-- AVERAGE FEES PER STUDENT



WITH FIXEDCOSTS AS (
    SELECT SUM(AMOUNT) AS FIXED_COSTS
    FROM EXPENSES
     WHERE DESCRIPTION IN ('Building & Construction', 'Salaries & Wages', 'Rent Expenses', 'Loans', 'Utilities', 'Miscallenous')
),
VARIABLEPERSTUDENT AS (
    SELECT SUM(AMOUNT) / 220 AS VAR_PER_STUDENT
    FROM EXPENSES
    WHERE DESCRIPTION IN ('Kitchen Expenses', 'Transport Expenses', 'Learning Materials', 'Maintenance Supplies')
),
FEESPERSTUDENT AS (
    SELECT AVG(TOTAL_FEES) AS FEE
    FROM FEES
)

SELECT 
    FIXED_COSTS / (FEE - VAR_PER_STUDENT) AS BREAK_EVEN_STUDENTS
FROM FIXEDCOSTS, VARIABLEPERSTUDENT, FEESPERSTUDENT;
-- BREAK-EVEN STUDENTS